sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: sssycamore
    region: cn-beijing
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wx10c938d037e96e02
    secret: dd0bdc4ad59eaed4e685affd9d28ee79
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: hBUdASzu9mrgKgYjJT1huOcHsfAFImye